# Generated by Django 4.1.2 on 2022-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="buyer",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="property",
            name="property_status",
            field=models.CharField(default="NOT BOOKED", max_length=100),
        ),
        migrations.AlterField(
            model_name="property", name="pincode", field=models.IntegerField(),
        ),
    ]
