# Generated by Django 4.1.2 on 2022-10-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_buyer_property_property_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="buyer",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
