# Generated by Django 4.1.2 on 2022-10-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_property_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="amount",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
